development:
  perform_authentication: false
  
  facebook_redirect_url: http://localhost:3000/auth/facebook

test:
  perform_authentication: false
  
  facebook_redirect_url: http://localhost:3000/auth/facebook

production:
  perform_authentication: false
  username: admin
  password: secret
  
  facebook_redirect_url: http://www.molamp.net/auth/facebook
